/**
 * Shell completion, generated from the live `commander` program.
 *
 * The flag set is now large enough that typing it from memory is the slow part
 * of using the CLI, so `api-recon completion <shell>` prints a script for bash,
 * zsh, or fish. The scripts are built from the same `Command` the CLI parses
 * with, so a flag added there shows up in completions without a second list to
 * maintain; only the *values* a flag accepts are declared here, since commander
 * knows a flag takes an argument but not that `--browser` means an engine.
 *
 * The output is environment-independent, so it can be committed or generated at
 * install time and compared in a test.
 */

import type { Command } from 'commander';

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

/** The committed script for each shell, under `completions/`. */
export const COMPLETION_FILENAMES: Record<CompletionShell, string> = {
  bash: 'api-recon.bash',
  zsh: '_api-recon',
  fish: 'api-recon.fish',
};

/** True when `value` names a shell this command can generate for. */
export function isCompletionShell(value: unknown): value is CompletionShell {
  return typeof value === 'string' && (COMPLETION_SHELLS as readonly string[]).includes(value);
}

/** The report formats, in the order `--formats` documents them. */
const FORMAT_VALUES = ['json', 'md', 'html', 'pdf', 'openapi', 'dashboard'] as const;

/** Flags whose values are a closed set the shell can offer. */
const CHOICE_VALUES: Record<string, readonly string[]> = {
  '--browser': ['chromium', 'firefox', 'webkit'],
  '--preset': ['quick', 'deep', 'ci'],
  '--print': ['md', 'json', 'openapi', 'html'],
  '--formats': FORMAT_VALUES,
};

/** Flags that name a file, or a directory. */
const FILE_FLAGS = new Set(['--auth', '--login', '--actions', '--config', '--diff', '--baseline']);
const DIR_FLAGS = new Set(['--out']);

interface FlagSpec {
  long: string;
  short?: string;
  description: string;
  takesValue: boolean;
}

interface CommandSpec {
  name: string;
  description: string;
}

interface CompletionSpec {
  commands: CommandSpec[];
  flags: FlagSpec[];
}

/** Walk the program and every subcommand into a flat, deduplicated model. */
export function buildCompletionSpec(program: Command): CompletionSpec {
  const commands = program.commands.map((cmd) => ({
    name: cmd.name(),
    description: clean(cmd.description()),
  }));

  const flags = new Map<string, FlagSpec>();
  const addFlags = (command: Command): void => {
    for (const option of command.options) {
      const long = option.long;
      if (!long || flags.has(long)) continue;
      flags.set(long, {
        long,
        ...(option.short ? { short: option.short } : {}),
        description: clean(option.description),
        // `<arg>` is required, `[arg]` optional; either way the flag takes one.
        takesValue: /[<[]/.test(option.flags),
      });
    }
  };
  addFlags(program);
  for (const command of program.commands) addFlags(command);

  return { commands, flags: [...flags.values()] };
}

/** A bash script: a completion function plus the `complete` registration. */
function bashCompletion(spec: CompletionSpec): string {
  const flagWords = [
    ...spec.flags.flatMap((flag) => [flag.long, ...(flag.short ? [flag.short] : [])]),
    '--help',
    '-h',
  ];

  const valueArms = Object.entries(CHOICE_VALUES).map(
    ([flag, values]) =>
      `    ${flag}) COMPREPLY=( $(compgen -W "${values.join(' ')}" -- "\${cur}") ); return 0 ;;`,
  );
  if (FILE_FLAGS.size > 0) {
    valueArms.push(
      `    ${[...FILE_FLAGS].join('|')}) COMPREPLY=( $(compgen -f -- "\${cur}") ); return 0 ;;`,
    );
  }
  if (DIR_FLAGS.size > 0) {
    valueArms.push(
      `    ${[...DIR_FLAGS].join('|')}) COMPREPLY=( $(compgen -d -- "\${cur}") ); return 0 ;;`,
    );
  }

  return [
    '# api-recon bash completion — generated by `api-recon completion bash`.',
    '# Install: source <(api-recon completion bash), or drop it in bash_completion.d.',
    '_api_recon_completions() {',
    '  local cur prev',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '',
    `  local flags="${flagWords.join(' ')}"`,
    '',
    '  case "${prev}" in',
    ...valueArms,
    '  esac',
    '',
    '  if [[ "${cur}" == -* ]]; then',
    '    COMPREPLY=( $(compgen -W "${flags}" -- "${cur}") )',
    '    return 0',
    '  fi',
    '',
    '  if [[ "${COMP_WORDS[1]}" == "completion" ]]; then',
    `    COMPREPLY=( $(compgen -W "${COMPLETION_SHELLS.join(' ')}" -- "\${cur}") )`,
    '    return 0',
    '  fi',
    '',
    '  # The first positional word is the subcommand; later ones are the seed URL.',
    '  local i seen=0',
    '  for (( i=1; i < COMP_CWORD; i++ )); do',
    '    [[ "${COMP_WORDS[i]}" != -* ]] && seen=1',
    '  done',
    '  if (( seen == 0 )); then',
    `    COMPREPLY=( $(compgen -W "${spec.commands.map((c) => c.name).join(' ')}" -- "\${cur}") )`,
    '  fi',
    '  return 0',
    '}',
    'complete -o default -F _api_recon_completions api-recon',
    '',
  ].join('\n');
}

/** A zsh script: a `#compdef` function using `_describe`, `_values`, `_files`. */
function zshCompletion(spec: CompletionSpec): string {
  const commands = spec.commands
    .map((command) => `    ${zshEntry(command.name, command.description)}`)
    .join('\n');
  const flags = spec.flags
    .map((flag) => `    ${zshEntry(flag.long, flag.description)}`)
    .concat(`    ${zshEntry('--help', 'show help for a command')}`)
    .join('\n');

  const valueArms = [
    ...Object.entries(CHOICE_VALUES).map(
      ([flag, values]) => `    ${flag}) _values 'value' ${values.join(' ')}; return ;;`,
    ),
    `    ${[...FILE_FLAGS, ...DIR_FLAGS].join('|')}) _files; return ;;`,
  ];

  return [
    '#compdef api-recon',
    '# api-recon zsh completion — generated by `api-recon completion zsh`.',
    '# Install: api-recon completion zsh > "${fpath[1]}/_api-recon"',
    '_api_recon() {',
    '  local -a commands flags',
    '  commands=(',
    commands,
    '  )',
    '  flags=(',
    flags,
    '  )',
    '',
    '  if [[ "${words[2]}" == "completion" ]]; then',
    `    _values 'shell' ${COMPLETION_SHELLS.join(' ')}`,
    '    return',
    '  fi',
    '',
    '  case "${words[CURRENT-1]}" in',
    ...valueArms,
    '  esac',
    '',
    '  if (( CURRENT == 2 )); then',
    "    _describe 'command' commands",
    '    return',
    '  fi',
    '',
    "  _describe 'option' flags",
    '}',
    '_api_recon "$@"',
    '',
  ].join('\n');
}

/** A fish script: one `complete` line per flag, with descriptions. */
function fishCompletion(spec: CompletionSpec): string {
  const lines = [
    '# api-recon fish completion — generated by `api-recon completion fish`.',
    '# Install: api-recon completion fish > ~/.config/fish/completions/api-recon.fish',
    'complete -c api-recon -f',
    '',
  ];

  for (const command of spec.commands) {
    lines.push(
      `complete -c api-recon -n '__fish_use_subcommand' -a ${command.name} -d ${quoteFish(command.description)}`,
    );
  }
  if (spec.commands.some((command) => command.name === 'completion')) {
    lines.push(
      `complete -c api-recon -n '__fish_seen_subcommand_from completion' -a ${quoteFish(
        COMPLETION_SHELLS.join(' '),
      )} -d 'shell to generate for'`,
    );
  }

  lines.push('');
  for (const flag of spec.flags) {
    lines.push(`complete -c api-recon${fishFlag(flag)}${fishValue(flag)} -d ${quoteFish(flag.description)}`);
  }

  lines.push('');
  return lines.join('\n');
}

/** ` -l long -s short`, the long name first. */
function fishFlag(flag: FlagSpec): string {
  const long = flag.long.replace(/^--/, '');
  const short = flag.short ? ` -s ${flag.short.replace(/^-/, '')}` : '';
  return ` -l ${long}${short}`;
}

/** How fish should complete a flag's value, if it takes one. */
function fishValue(flag: FlagSpec): string {
  if (CHOICE_VALUES[flag.long]) {
    return ` -r -xa ${quoteFish(CHOICE_VALUES[flag.long]!.join(' '))}`;
  }
  if (FILE_FLAGS.has(flag.long) || DIR_FLAGS.has(flag.long)) return ' -r -F';
  if (flag.takesValue) return ' -r';
  return '';
}

function clean(text: string | undefined): string {
  return (text ?? '').replace(/\s+/g, ' ').trim();
}

/**
 * A zsh `_describe` entry: `'name:description'`. The separating colon is kept,
 * but colons and brackets inside the description would confuse `_describe`, so
 * they are flattened to spaces first.
 */
function zshEntry(name: string, description: string): string {
  const desc = clean(description).replace(/[[\]:]/g, ' ');
  return `'${name.replace(/'/g, `'\\''`)}:${desc.replace(/'/g, `'\\''`)}'`;
}

/** Single-quote a description for fish. */
function quoteFish(text: string): string {
  return `'${clean(text).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** The completion script for one shell. */
export function completionScript(shell: CompletionShell, program: Command): string {
  const spec = buildCompletionSpec(program);
  switch (shell) {
    case 'bash':
      return bashCompletion(spec);
    case 'zsh':
      return zshCompletion(spec);
    case 'fish':
      return fishCompletion(spec);
  }
}
