/**
 * The page → request graph.
 *
 * Every captured call records the page that triggered it, and the analyzer
 * keeps that as `Endpoint.triggeredBy` — a relationship the report otherwise
 * makes the reader reconstruct by reading URLs out of two tables. This module
 * turns it into a small graph, rendered as Mermaid for Markdown and as inline
 * SVG for the HTML artifacts (no Mermaid runtime, so both stay self-contained
 * and work offline).
 *
 * Both renderers are pure and the layout is deterministic, so the example
 * reports can be regenerated byte-for-byte.
 */

import type { ReconReport } from '../types.js';

/** One box in the graph: a page, or a request made from one. */
export interface RequestGraphNode {
  /** Stable id within the graph — `p0`, `e3` — so a label can contain anything. */
  id: string;
  label: string;
  /** For a request, the captured call count; for a page, how many requests it made. */
  calls: number;
}

export interface RequestGraphEdge {
  from: string;
  to: string;
  calls: number;
}

export interface RequestGraph {
  pages: RequestGraphNode[];
  requests: RequestGraphNode[];
  edges: RequestGraphEdge[];
  /** Requests found but left out to keep the drawing readable. */
  omittedPages: number;
  omittedRequests: number;
}

export interface RequestGraphOptions {
  maxPages?: number;
  maxRequests?: number;
}

/**
 * A graph of every page that triggered at least one captured request.
 *
 * Pages are ranked by how many requests they made and requests by how often
 * they were called, and the tail is dropped rather than drawn: a hundred-node
 * hairball communicates less than a table does. Anything dropped is counted so
 * the report can say so.
 */
export function buildRequestGraph(
  report: ReconReport,
  options: RequestGraphOptions = {},
): RequestGraph {
  const maxPages = options.maxPages ?? 20;
  const maxRequests = options.maxRequests ?? 40;
  const seedHost = hostOf(report.meta.seedUrl);

  // Group endpoints by the page that caused them. An endpoint with no recorded
  // trigger has no edge to draw, so it is left out of the picture.
  const byPage = new Map<string, RequestGraphNode[]>();
  for (const endpoint of report.endpoints) {
    for (const trigger of endpoint.triggeredBy) {
      const list = byPage.get(trigger);
      const node: RequestGraphNode = {
        id: '',
        label: `${endpoint.method} ${endpoint.urlPattern}`,
        calls: endpoint.count,
      };
      if (list) list.push(node);
      else byPage.set(trigger, [node]);
    }
  }

  const pages = [...byPage.entries()]
    .map(([url, requests]) => ({
      url,
      label: pageLabel(url, seedHost),
      requests,
    }))
    .sort((a, b) => b.requests.length - a.requests.length || a.label.localeCompare(b.label));

  const keptPages = pages.slice(0, maxPages);

  // Requests across the kept pages, most-called first, capped once.
  const requestSeen = new Map<string, RequestGraphNode>();
  for (const page of keptPages) {
    for (const request of page.requests) {
      const existing = requestSeen.get(request.label);
      if (existing) existing.calls = Math.max(existing.calls, request.calls);
      else requestSeen.set(request.label, { ...request });
    }
  }
  const requests = [...requestSeen.values()].sort(
    (a, b) => b.calls - a.calls || a.label.localeCompare(b.label),
  );
  const keptRequests = requests.slice(0, maxRequests);

  const pageNodes: RequestGraphNode[] = keptPages.map((page, index) => ({
    id: `p${index}`,
    label: page.label,
    calls: page.requests.length,
  }));
  const requestNodes: RequestGraphNode[] = keptRequests.map((request, index) => ({
    ...request,
    id: `e${index}`,
  }));

  const requestIdByLabel = new Map(requestNodes.map((node) => [node.label, node.id]));
  const edges: RequestGraphEdge[] = [];
  keptPages.forEach((page, pageIndex) => {
    for (const request of page.requests) {
      const to = requestIdByLabel.get(request.label);
      if (!to) continue;
      edges.push({ from: `p${pageIndex}`, to, calls: request.calls });
    }
  });

  return {
    pages: pageNodes,
    requests: requestNodes,
    edges,
    omittedPages: pages.length - keptPages.length,
    omittedRequests: requests.length - keptRequests.length,
  };
}

/**
 * A page's label: its path, with the host in front when the page was not on the
 * seed host (so a third-party page is not shown as if it were part of the site).
 */
function pageLabel(url: string, seedHost: string): string {
  try {
    const parsed = new URL(url);
    const path = `${parsed.pathname}${parsed.search}`;
    return parsed.host === seedHost ? path : `${parsed.host}${path}`;
  } catch {
    return url;
  }
}

function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return '';
  }
}

/** Mermaid `flowchart LR`, the form GitHub and most Markdown viewers render. */
export function toMermaid(graph: RequestGraph): string {
  const lines = ['flowchart LR'];
  for (const node of graph.pages) {
    lines.push(`  ${node.id}["${mermaidLabel(node.label)}"]`);
  }
  for (const node of graph.requests) {
    lines.push(`  ${node.id}["${mermaidLabel(node.label)}"]`);
  }
  for (const edge of graph.edges) {
    lines.push(`  ${edge.from} --> ${edge.to}`);
  }
  return lines.join('\n');
}

/** Mermaid reads `#quot;` etc. inside a quoted label; quotes must not leak out. */
function mermaidLabel(label: string): string {
  return label.replace(/"/g, '#quot;').replace(/</g, '#lt;').replace(/>/g, '#gt;');
}

// ---- inline SVG ------------------------------------------------------------

const NODE_HEIGHT = 26;
const NODE_GAP = 10;
const COLUMN_GAP = 170;
const PADDING = 14;
const CHAR_WIDTH = 6.6;
const MIN_PAGE_WIDTH = 150;
const MIN_REQUEST_WIDTH = 180;
const MAX_NODE_WIDTH = 430;

/**
 * Render the graph as a standalone inline SVG: pages in a left column, requests
 * in a right column, one curve per relationship. The two columns are centred
 * against each other, and a curve's width grows with the call count, so the
 * busiest relationship is the one the eye finds first.
 */
export function renderRequestGraphSvg(graph: RequestGraph): string {
  const pageWidth = columnWidth(graph.pages, MIN_PAGE_WIDTH);
  const requestWidth = columnWidth(graph.requests, MIN_REQUEST_WIDTH);
  const pageHeight = columnHeight(graph.pages.length);
  const requestHeight = columnHeight(graph.requests.length);
  const contentHeight = Math.max(pageHeight, requestHeight);
  const width = PADDING * 2 + pageWidth + COLUMN_GAP + requestWidth;
  const height = PADDING * 2 + contentHeight;

  const pageX = PADDING;
  const requestX = PADDING + pageWidth + COLUMN_GAP;
  const pageTop = PADDING + (contentHeight - pageHeight) / 2;
  const requestTop = PADDING + (contentHeight - requestHeight) / 2;

  const centers = new Map<string, number>();
  graph.pages.forEach((node, index) => {
    centers.set(node.id, pageTop + index * (NODE_HEIGHT + NODE_GAP) + NODE_HEIGHT / 2);
  });
  graph.requests.forEach((node, index) => {
    centers.set(node.id, requestTop + index * (NODE_HEIGHT + NODE_GAP) + NODE_HEIGHT / 2);
  });

  const edges = graph.edges
    .map((edge) => {
      const fromY = centers.get(edge.from);
      const toY = centers.get(edge.to);
      if (fromY === undefined || toY === undefined) return '';
      const fromX = pageX + pageWidth;
      const bend = COLUMN_GAP / 2;
      return (
        `<path class="rg-edge" stroke-width="${edgeWidth(edge.calls)}" d="` +
        `M ${round(fromX)} ${round(fromY)} C ${round(fromX + bend)} ${round(fromY)}, ` +
        `${round(requestX - bend)} ${round(toY)}, ${round(requestX)} ${round(toY)}" />`
      );
    })
    .join('');

  const pages = graph.pages
    .map((node, index) =>
      nodeMarkup('rg-page', node, pageX, pageTop + index * (NODE_HEIGHT + NODE_GAP), pageWidth),
    )
    .join('');
  const requests = graph.requests
    .map((node, index) =>
      nodeMarkup(
        'rg-request',
        node,
        requestX,
        requestTop + index * (NODE_HEIGHT + NODE_GAP),
        requestWidth,
      ),
    )
    .join('');

  return (
    `<svg class="request-graph" viewBox="0 0 ${round(width)} ${round(height)}" ` +
    `width="${round(width)}" height="${round(height)}" role="img" ` +
    `aria-label="Pages and the requests they triggered">` +
    `<title>Pages and the requests they triggered</title>` +
    `<g class="rg-edges">${edges}</g>` +
    `<g class="rg-nodes">${pages}${requests}</g>` +
    `</svg>`
  );
}

function nodeMarkup(kind: string, node: RequestGraphNode, x: number, y: number, width: number): string {
  return (
    `<g class="rg-node ${kind}" transform="translate(${round(x)},${round(y)})">` +
    `<rect width="${round(width)}" height="${NODE_HEIGHT}" rx="7" />` +
    `<text x="10" y="17">${escapeHtml(clip(node.label, width))}</text>` +
    `<title>${escapeHtml(node.label)}</title>` +
    `</g>`
  );
}

/** Estimate the widest label; SVG cannot measure text before it is laid out. */
function columnWidth(nodes: RequestGraphNode[], min: number): number {
  const longest = nodes.reduce((max, node) => Math.max(max, node.label.length), 0);
  return Math.min(MAX_NODE_WIDTH, Math.max(min, Math.round(longest * CHAR_WIDTH) + 24));
}

function columnHeight(count: number): number {
  return count > 0 ? count * NODE_HEIGHT + (count - 1) * NODE_GAP : 0;
}

/** A busy relationship draws heavier; the scale is logarithmic, not linear. */
function edgeWidth(calls: number): string {
  return (1 + Math.min(1.8, Math.log10(1 + Math.max(0, calls)))).toFixed(1);
}

/** Clip a label that would overrun its box; the full text stays in the `<title>`. */
function clip(label: string, width: number): string {
  const fits = Math.floor((width - 20) / CHAR_WIDTH);
  return label.length <= fits ? label : `${label.slice(0, Math.max(1, fits - 1))}…`;
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
