/** Markdown reporter. Sections follow the report contract in the README. */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { CapturedWebSocket, Endpoint, ReconReport, ReportDiff } from '../types.js';
import { CATEGORIES } from '../types.js';
import { formatDuration, truncate } from '../utils/misc.js';
import { FORMAT_FILENAMES } from './json.js';

const MAX_SAMPLE_CHARS = 2000;

/** Escape a value for a Markdown table cell (and neutralise raw HTML). */
function cell(value: string): string {
  return value
    .replace(/\|/g, '\\|')
    .replace(/[\r\n]+/g, ' ')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function code(value: string, lang = 'json'): string {
  return `\`\`\`${lang}\n${value}\n\`\`\``;
}

function headersBlock(headers: Record<string, string>): string {
  const entries = Object.entries(headers);
  if (entries.length === 0) return '_none captured_';
  return code(entries.map(([k, v]) => `${k}: ${v}`).join('\n'), 'http');
}

export function renderMarkdown(report: ReconReport): string {
  const out: string[] = [];
  const { meta } = report;

  out.push('# API recon report');
  out.push('');
  out.push(
    `Generated by **api-recon** v${meta.apiReconVersion} for \`${meta.seedUrl}\`.`,
  );
  out.push('');

  // ---- 1. Overview ------------------------------------------------------
  out.push('## 1. Overview');
  out.push('');
  out.push('| Field | Value |');
  out.push('| --- | --- |');
  out.push(`| Seed URL | \`${cell(meta.seedUrl)}\` |`);
  out.push(`| Started at | ${cell(meta.startedAt)} |`);
  out.push(`| Duration | ${formatDuration(meta.durationMs)} |`);
  out.push(`| Pages visited | ${meta.pagesVisited} |`);
  out.push(`| Endpoints discovered | ${report.endpoints.length} |`);
  out.push(`| Redaction | ${report.safety.redact ? 'enabled' : 'disabled'} |`);
  out.push('');

  // ---- 2. Detected technologies ----------------------------------------
  out.push('## 2. Detected Technologies');
  out.push('');
  if (report.technologies.length === 0) {
    out.push('_No technologies were fingerprinted from the observed evidence._');
  } else {
    out.push('| Technology | Category | Evidence |');
    out.push('| --- | --- | --- |');
    for (const tech of report.technologies) {
      out.push(`| ${cell(tech.name)} | ${cell(tech.category)} | ${cell(tech.evidence)} |`);
    }
  }
  out.push('');

  // ---- 3. Endpoint summary by category ---------------------------------
  out.push('## 3. Endpoint Summary by Category');
  out.push('');
  for (const category of CATEGORIES) {
    const endpoints = report.endpoints.filter((e) => e.category === category);
    if (endpoints.length === 0) continue;
    out.push(`### ${category} (${endpoints.length})`);
    out.push('');
    out.push('| Method | Path | Status | Count |');
    out.push('| --- | --- | --- | --- |');
    for (const e of endpoints) {
      out.push(`| ${e.method} | \`${cell(e.urlPattern)}\` | ${e.statusCodes.join(', ')} | ${e.count} |`);
    }
    out.push('');
  }

  // ---- 4. Detailed endpoints -------------------------------------------
  out.push('## 4. Detailed Endpoints');
  out.push('');
  if (report.endpoints.length === 0) {
    out.push('_No XHR/fetch traffic was captured._');
    out.push('');
  }
  for (const endpoint of report.endpoints) {
    out.push(...detailedEndpoint(endpoint));
  }

  // ---- 5. Authentication flows -----------------------------------------
  const auth = report.endpoints.filter((e) => e.category === 'authentication');
  out.push('## 5. Authentication Flows Observed');
  out.push('');
  if (auth.length === 0) {
    out.push('_No authentication endpoints were observed during this scan._');
  } else {
    for (const e of auth) {
      out.push(`- \`${e.method} ${e.urlPattern}\` → ${e.statusCodes.join(', ')} (${e.count} call(s))`);
    }
  }
  out.push('');

  // ---- 6. Third-party calls --------------------------------------------
  const thirdParty = report.endpoints.filter((e) => e.category === 'third-party');
  if (thirdParty.length > 0) {
    out.push('## 6. Third-party Calls');
    out.push('');
    out.push('| Method | Path | Origins | Count |');
    out.push('| --- | --- | --- | --- |');
    for (const e of thirdParty) {
      out.push(
        `| ${e.method} | \`${cell(e.urlPattern)}\` | ${cell(e.origins.join(', '))} | ${e.count} |`,
      );
    }
    out.push('');
  }

  // ---- 7. Safety notes --------------------------------------------------
  out.push('## 7. Safety Notes');
  out.push('');
  out.push(`- robots.txt respected: **${report.safety.robotsRespected ? 'yes' : 'no'}**`);
  if (report.safety.robotsSkippedPaths.length > 0) {
    out.push(`- Paths skipped because of robots.txt:`);
    for (const p of report.safety.robotsSkippedPaths) out.push(`  - \`${cell(p)}\``);
  }
  out.push(`- Minimum request interval: ${report.safety.rateLimitMs}ms`);
  out.push(`- Response body capture cap: ${Math.round(report.safety.maxBodyBytes / 1024)} KB per response`);
  out.push(`- Sensitive headers redacted: **${report.safety.redact ? 'yes' : 'no'}**`);
  out.push(`- Local/private targets allowed: **${report.safety.allowLocal ? 'yes' : 'no'}**`);
  out.push('');

  // ---- 8. WebSocket traffic (only when something was captured) ----------
  if (report.webSockets.length > 0) out.push(...webSocketSection(report.webSockets));

  // ---- 9. Changes since baseline (diff mode only) -----------------------
  // Appended rather than inserted so the documented numbering of sections
  // 1–7 never shifts; it is absent unless a baseline was supplied.
  if (report.diff) out.push(...diffSection(report.diff));

  out.push('_api-recon observes and documents only. It does not bypass authentication, CAPTCHAs, or bot protections._');
  out.push('');

  return out.join('\n');
}

function webSocketSection(webSockets: CapturedWebSocket[]): string[] {
  const out: string[] = [];
  out.push('## 8. WebSocket Traffic');
  out.push('');
  out.push(
    `_${webSockets.length} connection(s) observed. Frames are redacted and size-capped like request and response bodies._`,
  );
  out.push('');

  for (const ws of webSockets) {
    out.push(`### \`${cell(ws.url)}\``);
    out.push('');
    out.push('| Field | Value |');
    out.push('| --- | --- |');
    out.push(`| Triggered by | ${cell(ws.triggeredBy)} |`);
    out.push(`| Frames | ${ws.frameCount} (${ws.sentCount} sent, ${ws.receivedCount} received) |`);
    if (ws.framesTruncated) {
      out.push(`| Note | only the first ${ws.frames.length} frame(s) were stored |`);
    }
    out.push('');

    if (ws.frames.length === 0) {
      out.push('_No frames were captured on this connection._');
      out.push('');
      continue;
    }

    out.push('| Direction | Type | Size | Payload sample |');
    out.push('| --- | --- | --- | --- |');
    for (const frame of ws.frames) {
      const direction = frame.direction === 'sent' ? 'sent' : 'received';
      const payload = frame.payloadSample
        ? cell(truncate(frame.payloadSample, MAX_SAMPLE_CHARS / 8)) + (frame.truncated ? ' …' : '')
        : '_not stored_ (capture budget exhausted)';
      out.push(`| ${direction} | ${frame.type} | ${frame.size} B | ${payload} |`);
    }
    out.push('');
  }

  return out;
}

function diffSection(diff: ReportDiff): string[] {
  const out: string[] = [];
  out.push('## 9. Changes Since Baseline');
  out.push('');
  out.push(
    `Compared with a scan of \`${cell(diff.baseline.seedUrl)}\` from ${cell(diff.baseline.startedAt)} ` +
      `(api-recon v${cell(diff.baseline.apiReconVersion)}).`,
  );
  out.push('');

  if (!diff.hasChanges) {
    out.push('_No endpoint changes were detected._');
    out.push('');
    return out;
  }

  const { added, removed, changed, breaking } = diff.counts;
  out.push(
    `**${added}** added, **${removed}** removed, **${changed}** changed — **${breaking}** classified as breaking.`,
  );
  out.push('');
  out.push('| Change | Endpoint | Breaking | Details |');
  out.push('| --- | --- | --- | --- |');
  for (const change of diff.changes) {
    out.push(
      `| ${change.kind} | \`${cell(change.id)}\` | ${change.breaking ? 'yes' : 'no'} | ${cell(
        change.details.join('; '),
      )} |`,
    );
  }
  out.push('');
  out.push(
    '_A scan samples whatever traffic it happens to trigger, so an endpoint listed as removed may simply not have been exercised this time._',
  );
  out.push('');
  return out;
}

function detailedEndpoint(endpoint: Endpoint): string[] {
  const lines: string[] = [];
  lines.push(`### \`${endpoint.method} ${endpoint.urlPattern}\``);
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Category | ${endpoint.category} |`);
  lines.push(`| Occurrences | ${endpoint.count} |`);
  lines.push(`| Status codes | ${endpoint.statusCodes.join(', ')} |`);
  lines.push(`| MIME types | ${cell(endpoint.mimeTypes.join(', ') || 'unknown')} |`);
  lines.push(`| Origins | ${cell(endpoint.origins.join(', '))} |`);
  lines.push(`| Triggered by | ${cell(endpoint.triggeredBy.join(', '))} |`);
  if (endpoint.graphql) {
    const operations = endpoint.graphql.operations.map(
      (op) => `${op.name ? `\`${op.name}\`` : 'anonymous'} (${op.type})`,
    );
    lines.push(
      `| GraphQL introspection | ${endpoint.graphql.introspection ? 'yes — the schema is exposed' : 'no'} |`,
    );
    lines.push(`| GraphQL operations | ${operations.join(', ') || '—'} |`);
  }
  if (endpoint.pathParams.length > 0) {
    lines.push(`| Path parameters | ${endpoint.pathParams.map((p) => `\`${p}\``).join(', ')} |`);
  }
  if (endpoint.queryParams.length > 0) {
    lines.push(
      `| Query parameters | ${endpoint.queryParams
        .map((q) => `\`${q.name}\`${q.sampleValues.length ? ` (e.g. ${q.sampleValues.join(', ')})` : ''}`)
        .join(', ')} |`,
    );
  }
  lines.push('');

  lines.push('**Request headers**');
  lines.push('');
  lines.push(headersBlock(endpoint.requestHeaders));
  lines.push('');
  lines.push('**Response headers**');
  lines.push('');
  lines.push(headersBlock(endpoint.responseHeaders));
  lines.push('');

  if (endpoint.requestBodySample) {
    lines.push('**Request body (sample)**');
    lines.push('');
    lines.push(code(truncate(endpoint.requestBodySample, MAX_SAMPLE_CHARS)));
    lines.push('');
  }
  if (endpoint.responseBodySample) {
    lines.push('**Response body (sample)**');
    lines.push('');
    lines.push(code(truncate(endpoint.responseBodySample, MAX_SAMPLE_CHARS)));
    lines.push('');
  }
  if (endpoint.responseSchema) {
    lines.push('**Inferred response schema**');
    lines.push('');
    lines.push(code(JSON.stringify(endpoint.responseSchema, null, 2)));
    lines.push('');
  }
  return lines;
}

export async function writeMarkdownReport(markdown: string, outDir: string): Promise<string> {
  await mkdir(outDir, { recursive: true });
  const file = join(outDir, FORMAT_FILENAMES.md);
  await writeFile(file, markdown, 'utf8');
  return file;
}
