/** Markdown reporter. Sections follow the report contract in the README. */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type {
  CacheInfo,
  CapturedWebSocket,
  Endpoint,
  Finding,
  FindingSeverity,
  PercentileStats,
  ReconReport,
  ReportDiff,
  Resource,
} from '../types.js';
import { CATEGORIES } from '../types.js';
import { describeGapReason } from '../core/schemaInference.js';
import { formatBytes, formatDuration, truncate } from '../utils/misc.js';
import { FORMAT_FILENAMES } from './json.js';

const MAX_SAMPLE_CHARS = 2000;

/** Escape a value for a Markdown table cell (and neutralise raw HTML). */
function cell(value: string): string {
  return value
    .replace(/\|/g, '\\|')
    .replace(/[\r\n]+/g, ' ')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function code(value: string, lang = 'json'): string {
  return `\`\`\`${lang}\n${value}\n\`\`\``;
}

function headersBlock(headers: Record<string, string>): string {
  const entries = Object.entries(headers);
  if (entries.length === 0) return '_none captured_';
  return code(entries.map(([k, v]) => `${k}: ${v}`).join('\n'), 'http');
}

export function renderMarkdown(report: ReconReport): string {
  const out: string[] = [];
  const { meta } = report;

  out.push('# API recon report');
  out.push('');
  out.push(
    `Generated by **api-recon** v${meta.apiReconVersion} for \`${meta.seedUrl}\`.`,
  );
  out.push('');

  // ---- 1. Overview ------------------------------------------------------
  out.push('## 1. Overview');
  out.push('');
  out.push('| Field | Value |');
  out.push('| --- | --- |');
  out.push(`| Seed URL | \`${cell(meta.seedUrl)}\` |`);
  out.push(`| Started at | ${cell(meta.startedAt)} |`);
  out.push(`| Duration | ${formatDuration(meta.durationMs)} |`);
  out.push(`| Pages visited | ${meta.pagesVisited} |`);
  out.push(`| Browser engine | ${cell(meta.engine)} |`);
  out.push(`| Endpoints discovered | ${report.endpoints.length} |`);
  out.push(`| Redaction | ${report.safety.redact ? 'enabled' : 'disabled'} |`);
  out.push('');

  // ---- 2. Detected technologies ----------------------------------------
  out.push('## 2. Detected Technologies');
  out.push('');
  if (report.technologies.length === 0) {
    out.push('_No technologies were fingerprinted from the observed evidence._');
  } else {
    out.push('| Technology | Category | Evidence |');
    out.push('| --- | --- | --- |');
    for (const tech of report.technologies) {
      out.push(`| ${cell(tech.name)} | ${cell(tech.category)} | ${cell(tech.evidence)} |`);
    }
  }
  out.push('');

  // ---- 3. Endpoint summary by category ---------------------------------
  out.push('## 3. Endpoint Summary by Category');
  out.push('');
  for (const category of CATEGORIES) {
    const endpoints = report.endpoints.filter((e) => e.category === category);
    if (endpoints.length === 0) continue;
    out.push(`### ${category} (${endpoints.length})`);
    out.push('');
    out.push('| Method | Path | Status | Count |');
    out.push('| --- | --- | --- | --- |');
    for (const e of endpoints) {
      out.push(`| ${e.method} | \`${cell(e.urlPattern)}\` | ${e.statusCodes.join(', ')} | ${e.count} |`);
    }
    out.push('');
  }

  // ---- 4. Detailed endpoints -------------------------------------------
  out.push('## 4. Detailed Endpoints');
  out.push('');
  if (report.endpoints.length === 0) {
    out.push('_No XHR/fetch traffic was captured._');
    out.push('');
  }
  for (const endpoint of report.endpoints) {
    out.push(...detailedEndpoint(endpoint));
  }

  // ---- 5. Authentication flows -----------------------------------------
  const auth = report.endpoints.filter((e) => e.category === 'authentication');
  out.push('## 5. Authentication Flows Observed');
  out.push('');
  if (auth.length === 0) {
    out.push('_No authentication endpoints were observed during this scan._');
  } else {
    for (const e of auth) {
      out.push(`- \`${e.method} ${e.urlPattern}\` → ${e.statusCodes.join(', ')} (${e.count} call(s))`);
    }
  }
  out.push('');

  // ---- 6. Third-party calls --------------------------------------------
  const thirdParty = report.endpoints.filter((e) => e.category === 'third-party');
  if (thirdParty.length > 0) {
    out.push('## 6. Third-party Calls');
    out.push('');
    out.push('| Method | Path | Vendor | Origins | Count |');
    out.push('| --- | --- | --- | --- | --- |');
    for (const e of thirdParty) {
      out.push(
        `| ${e.method} | \`${cell(e.urlPattern)}\` | ${cell(e.vendor?.name ?? '—')} | ${cell(
          e.origins.join(', '),
        )} | ${e.count} |`,
      );
    }
    out.push('');
  }

  // ---- 7. Safety notes --------------------------------------------------
  out.push('## 7. Safety Notes');
  out.push('');
  out.push(`- robots.txt respected: **${report.safety.robotsRespected ? 'yes' : 'no'}**`);
  if (report.safety.robotsSkippedPaths.length > 0) {
    out.push(`- Paths skipped because of robots.txt:`);
    for (const p of report.safety.robotsSkippedPaths) out.push(`  - \`${cell(p)}\``);
  }
  out.push(`- Minimum request interval: ${report.safety.rateLimitMs}ms`);
  out.push(`- Response body capture cap: ${Math.round(report.safety.maxBodyBytes / 1024)} KB per response`);
  out.push(`- Sensitive headers redacted: **${report.safety.redact ? 'yes' : 'no'}**`);
  out.push(`- Local/private targets allowed: **${report.safety.allowLocal ? 'yes' : 'no'}**`);
  out.push('');

  // ---- 8. WebSocket traffic (only when something was captured) ----------
  if (report.webSockets.length > 0) out.push(...webSocketSection(report.webSockets));

  // ---- 9. Changes since baseline (diff mode only) -----------------------
  // Appended rather than inserted so the documented numbering of sections
  // 1–7 never shifts; it is absent unless a baseline was supplied.
  if (report.diff) out.push(...diffSection(report.diff));

  // ---- 10. Resource coverage (derived from the endpoints) ---------------
  if (report.resources?.length) out.push(...resourceSection(report.resources));

  // ---- 11. Performance (derived from the endpoints) ---------------------
  if (report.endpoints.some((e) => e.timing)) out.push(...performanceSection(report.endpoints));

  // ---- 12. Findings & next steps (derived from the scan) ----------------
  if (report.findings?.length) out.push(...findingsSection(report.findings));

  out.push('_api-recon observes and documents only. It does not bypass authentication, CAPTCHAs, or bot protections._');
  out.push('');

  return out.join('\n');
}

function resourceSection(resources: Resource[]): string[] {
  const out: string[] = [];
  out.push('## 10. Resource Coverage');
  out.push('');
  out.push(
    `_${resources.length} resource(s), grouped by collection root. A missing verb is one the REST ` +
      'convention expects for that path shape but no captured call exhibited._',
  );
  out.push('');
  for (const resource of resources) {
    out.push(`### \`${cell(resource.path)}\``);
    if (resource.categories.length) out.push('');
    if (resource.categories.length) out.push(`_Categories: ${cell(resource.categories.join(', '))}_`);
    out.push('');
    out.push('| Path | Methods | Missing |');
    out.push('| --- | --- | --- |');
    for (const path of resource.paths) {
      out.push(
        `| \`${cell(path.path)}\` | ${path.methods.join(', ') || '—'} | ${
          path.missingMethods.join(', ') || '—'
        } |`,
      );
    }
    out.push('');
  }
  return out;
}

/** Format `p50 / p95 / max` of a latency summary, in milliseconds. */
function formatMs(stats: PercentileStats): string {
  return `${stats.p50}ms / ${stats.p95}ms / ${stats.max}ms`;
}

/** Format `p50 / p95 / max` of a size summary. */
function formatSize(stats: PercentileStats): string {
  return `${formatBytes(stats.p50)} / ${formatBytes(stats.p95)} / ${formatBytes(stats.max)}`;
}

/** One line describing the cache-relevant headers that were present. */
function cacheSummary(cache: CacheInfo): string {
  const parts: string[] = [];
  if (cache.control) parts.push(`cache-control \`${cache.control}\``);
  if (cache.etag) parts.push(`etag \`${cache.etag}\``);
  if (cache.lastModified) parts.push(`last-modified \`${cache.lastModified}\``);
  if (cache.age !== undefined) parts.push(`age ${cache.age}s`);
  if (cache.vary) parts.push(`vary \`${cache.vary}\``);
  if (cache.status) parts.push(`status \`${cache.status}\``);
  return parts.map(cell).join(' · ');
}

const SEVERITY_LABELS: Array<[FindingSeverity, string]> = [
  ['high', 'High'],
  ['medium', 'Medium'],
  ['low', 'Low'],
  ['info', 'Info'],
];

/**
 * The report's close: what a reader should act on, grouped by severity. These
 * are heuristics over the capture, so the section is framed as review cues
 * rather than audit results.
 */
function findingsSection(findings: Finding[]): string[] {
  const out: string[] = [];
  out.push('## 12. Findings & Next Steps');
  out.push('');
  out.push(
    '_Heuristic review cues from this capture, not a security audit. Each is derived from the ' +
      'observations above._',
  );
  out.push('');

  for (const [severity, label] of SEVERITY_LABELS) {
    const group = findings.filter((finding) => finding.severity === severity);
    if (group.length === 0) continue;
    out.push(`### ${label}`);
    out.push('');
    for (const finding of group) {
      const scope =
        finding.endpoints.length > 0
          ? ` (${finding.endpoints.length} endpoint${finding.endpoints.length === 1 ? '' : 's'})`
          : ' (site-wide)';
      out.push(`- **${cell(finding.title)}**${scope}`);
      for (const detail of finding.details) out.push(`  - ${cell(detail)}`);
    }
    out.push('');
  }

  return out;
}

/**
 * A performance overview: the slowest endpoints and the largest responses. The
 * numbers come from whatever traffic the scan triggered, so they describe the
 * observed samples rather than a benchmark.
 */
function performanceSection(endpoints: Endpoint[]): string[] {
  const out: string[] = [];
  out.push('## 11. Performance');
  out.push('');
  out.push(
    '_Observed, not benchmarked: a scan samples whatever traffic it triggered. ' +
      'Body sizes are the captured bytes, so a size-capped body is a lower bound._',
  );
  out.push('');

  const slowest = endpoints
    .filter((e): e is Endpoint & { timing: PercentileStats } => e.timing !== undefined)
    .sort((a, b) => b.timing.p95 - a.timing.p95)
    .slice(0, 10);
  out.push('### Slowest endpoints (by p95)');
  out.push('');
  out.push('| Method | Path | p50 | p95 | max | Calls |');
  out.push('| --- | --- | --- | --- | --- | --- |');
  for (const endpoint of slowest) {
    out.push(
      `| ${endpoint.method} | \`${cell(endpoint.urlPattern)}\` | ${endpoint.timing.p50}ms | ` +
        `${endpoint.timing.p95}ms | ${endpoint.timing.max}ms | ${endpoint.count} |`,
    );
  }
  out.push('');

  const largest = endpoints
    .filter((e): e is Endpoint & { responseBytes: PercentileStats } => e.responseBytes !== undefined)
    .sort((a, b) => b.responseBytes.p95 - a.responseBytes.p95)
    .slice(0, 10);
  if (largest.length > 0) {
    out.push('### Largest responses (by p95)');
    out.push('');
    out.push('| Method | Path | p50 | p95 | max |');
    out.push('| --- | --- | --- | --- | --- |');
    for (const endpoint of largest) {
      out.push(
        `| ${endpoint.method} | \`${cell(endpoint.urlPattern)}\` | ` +
          `${formatSize(endpoint.responseBytes)} |`,
      );
    }
    out.push('');
  }

  return out;
}

function webSocketSection(webSockets: CapturedWebSocket[]): string[] {
  const out: string[] = [];
  out.push('## 8. WebSocket Traffic');
  out.push('');
  out.push(
    `_${webSockets.length} connection(s) observed. Frames are redacted and size-capped like request and response bodies._`,
  );
  out.push('');

  for (const ws of webSockets) {
    out.push(`### \`${cell(ws.url)}\``);
    out.push('');
    out.push('| Field | Value |');
    out.push('| --- | --- |');
    out.push(`| Triggered by | ${cell(ws.triggeredBy)} |`);
    out.push(`| Frames | ${ws.frameCount} (${ws.sentCount} sent, ${ws.receivedCount} received) |`);
    if (ws.framesTruncated) {
      out.push(`| Note | only the first ${ws.frames.length} frame(s) were stored |`);
    }
    out.push('');

    if (ws.frames.length === 0) {
      out.push('_No frames were captured on this connection._');
      out.push('');
      continue;
    }

    out.push('| Direction | Type | Size | Payload sample |');
    out.push('| --- | --- | --- | --- |');
    for (const frame of ws.frames) {
      const direction = frame.direction === 'sent' ? 'sent' : 'received';
      const payload = frame.payloadSample
        ? cell(truncate(frame.payloadSample, MAX_SAMPLE_CHARS / 8)) + (frame.truncated ? ' …' : '')
        : '_not stored_ (capture budget exhausted)';
      out.push(`| ${direction} | ${frame.type} | ${frame.size} B | ${payload} |`);
    }
    out.push('');

    if (ws.sentSchema) {
      out.push('**Inferred sent message schema**');
      out.push('');
      out.push(code(JSON.stringify(ws.sentSchema, null, 2)));
      out.push('');
    }
    if (ws.sentSchemaReason) {
      out.push(`_Sent message schema not fully observed — ${describeGapReason(ws.sentSchemaReason)}._`);
      out.push('');
    }
    if (ws.receivedSchema) {
      out.push('**Inferred received message schema**');
      out.push('');
      out.push(code(JSON.stringify(ws.receivedSchema, null, 2)));
      out.push('');
    }
    if (ws.receivedSchemaReason) {
      out.push(
        `_Received message schema not fully observed — ${describeGapReason(ws.receivedSchemaReason)}._`,
      );
      out.push('');
    }
  }

  return out;
}

function diffSection(diff: ReportDiff): string[] {
  const out: string[] = [];
  out.push('## 9. Changes Since Baseline');
  out.push('');
  out.push(
    `Compared with a scan of \`${cell(diff.baseline.seedUrl)}\` from ${cell(diff.baseline.startedAt)} ` +
      `(api-recon v${cell(diff.baseline.apiReconVersion)}).`,
  );
  out.push('');

  const baselineEngine = diff.baseline.engine;
  const currentEngine = diff.current.engine;
  if (baselineEngine && currentEngine && baselineEngine !== currentEngine) {
    out.push(
      `> **Warning:** the baseline ran in **${cell(baselineEngine)}** and this scan in ` +
        `**${cell(currentEngine)}**; some differences may be engine-specific rather than API changes.`,
    );
    out.push('');
  }

  if (!diff.hasChanges) {
    out.push('_No endpoint changes were detected._');
    out.push('');
    return out;
  }

  const { added, removed, changed, breaking } = diff.counts;
  out.push(
    `**${added}** added, **${removed}** removed, **${changed}** changed — **${breaking}** classified as breaking.`,
  );
  out.push('');
  out.push('| Change | Endpoint | Breaking | Details |');
  out.push('| --- | --- | --- | --- |');
  for (const change of diff.changes) {
    out.push(
      `| ${change.kind} | \`${cell(change.id)}\` | ${change.breaking ? 'yes' : 'no'} | ${cell(
        change.details.join('; '),
      )} |`,
    );
  }
  out.push('');
  out.push(
    '_A scan samples whatever traffic it happens to trigger, so an endpoint listed as removed may simply not have been exercised this time._',
  );
  out.push('');
  return out;
}

function detailedEndpoint(endpoint: Endpoint): string[] {
  const lines: string[] = [];
  lines.push(`### \`${endpoint.method} ${endpoint.urlPattern}\``);
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Category | ${endpoint.category} |`);
  if (endpoint.vendor) {
    lines.push(`| Vendor | ${cell(endpoint.vendor.name)} (${cell(endpoint.vendor.category)}) |`);
    lines.push(
      `| Vendor payload keys | ${
        endpoint.vendor.payloadKeys.length
          ? endpoint.vendor.payloadKeys.map((key) => `\`${cell(key)}\``).join(', ')
          : 'not observed'
      } |`,
    );
  }
  lines.push(`| Occurrences | ${endpoint.count} |`);
  lines.push(`| Status codes | ${endpoint.statusCodes.join(', ')} |`);
  lines.push(`| MIME types | ${cell(endpoint.mimeTypes.join(', ') || 'unknown')} |`);
  if (endpoint.timing) lines.push(`| Timing (p50 / p95 / max) | ${formatMs(endpoint.timing)} |`);
  if (endpoint.requestBytes) {
    lines.push(`| Request size (p50 / p95 / max) | ${formatSize(endpoint.requestBytes)} |`);
  }
  if (endpoint.responseBytes) {
    lines.push(`| Response size (p50 / p95 / max) | ${formatSize(endpoint.responseBytes)} |`);
  }
  if (endpoint.cache) lines.push(`| Cache | ${cacheSummary(endpoint.cache)} |`);
  lines.push(`| Origins | ${cell(endpoint.origins.join(', '))} |`);
  lines.push(`| Triggered by | ${cell(endpoint.triggeredBy.join(', '))} |`);
  if (endpoint.graphql) {
    const operations = endpoint.graphql.operations.map((op) => {
      const label = `${op.name ? `\`${op.name}\`` : 'anonymous'} (${op.type})`;
      const fields = op.selections?.length ? ` → ${op.selections.join(', ')}` : '';
      const args = op.arguments?.length ? ` (args: ${op.arguments.join(', ')})` : '';
      return `${label}${fields}${args}`;
    });
    lines.push(
      `| GraphQL introspection | ${endpoint.graphql.introspection ? 'yes — the schema is exposed' : 'no'} |`,
    );
    lines.push(`| GraphQL operations | ${operations.join(', ') || '—'} |`);
  }
  if (endpoint.pathParams.length > 0) {
    lines.push(`| Path parameters | ${endpoint.pathParams.map((p) => `\`${p}\``).join(', ')} |`);
  }
  if (endpoint.queryParams.length > 0) {
    lines.push(
      `| Query parameters | ${endpoint.queryParams
        .map((q) => `\`${q.name}\`${q.sampleValues.length ? ` (e.g. ${q.sampleValues.join(', ')})` : ''}`)
        .join(', ')} |`,
    );
  }
  lines.push('');

  lines.push('**Request headers**');
  lines.push('');
  lines.push(headersBlock(endpoint.requestHeaders));
  lines.push('');
  lines.push('**Response headers**');
  lines.push('');
  lines.push(headersBlock(endpoint.responseHeaders));
  lines.push('');

  if (endpoint.requestBodySample) {
    lines.push('**Request body (sample)**');
    lines.push('');
    lines.push(code(truncate(endpoint.requestBodySample, MAX_SAMPLE_CHARS)));
    lines.push('');
  }
  if (endpoint.responseBodySample) {
    lines.push('**Response body (sample)**');
    lines.push('');
    lines.push(code(truncate(endpoint.responseBodySample, MAX_SAMPLE_CHARS)));
    lines.push('');
  }
  if (endpoint.responseSchema) {
    lines.push('**Inferred response schema**');
    lines.push('');
    lines.push(code(JSON.stringify(endpoint.responseSchema, null, 2)));
    lines.push('');
    if (endpoint.responseSchemaReason) {
      lines.push(`_Partly observed — ${describeGapReason(endpoint.responseSchemaReason)}._`);
      lines.push('');
    }
  } else if (endpoint.responseSchemaReason) {
    lines.push(
      `_Response schema not inferred — ${describeGapReason(endpoint.responseSchemaReason)}._`,
    );
    lines.push('');
  }
  if (endpoint.errorResponses?.length) {
    lines.push('**Error responses**');
    lines.push('');
    for (const error of endpoint.errorResponses) {
      const mime = error.mimeTypes.length ? `, ${cell(error.mimeTypes.join(', '))}` : '';
      lines.push(`**\`${error.status}\`** — ${error.count} occurrence(s)${mime}`);
      lines.push('');
      if (error.bodySample) {
        lines.push(code(truncate(error.bodySample, MAX_SAMPLE_CHARS)));
        lines.push('');
      }
      if (error.schema) {
        lines.push(code(JSON.stringify(error.schema, null, 2)));
        lines.push('');
      }
      if (error.schemaReason) {
        lines.push(`_${describeGapReason(error.schemaReason)}._`);
        lines.push('');
      }
    }
  }
  return lines;
}

export async function writeMarkdownReport(markdown: string, outDir: string): Promise<string> {
  await mkdir(outDir, { recursive: true });
  const file = join(outDir, FORMAT_FILENAMES.md);
  await writeFile(file, markdown, 'utf8');
  return file;
}
