/** OpenAPI 3.0 reporter — best-effort spec derived from observed traffic. */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { dump as dumpYaml } from 'js-yaml';
import type { Endpoint, JsonSchemaLike, ReconReport } from '../types.js';
import { TOOL_VERSION } from '../version.js';
import { FORMAT_FILENAMES } from './json.js';

type Json = Record<string, unknown>;

const BODY_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

/** The format hints `stringFormatHint` can attach to a string schema. */
const FORMAT_HINTS = new Set([
  'uuid',
  'email',
  'uri',
  'date-time',
  'date',
  'time',
  'duration',
  'currency',
]);

export function buildOpenApi(report: ReconReport): Json {
  const host = safeHost(report.meta.seedUrl);
  const paths: Record<string, Json> = {};
  const tags = new Set<string>();

  for (const endpoint of report.endpoints) {
    const path = endpoint.urlPattern.startsWith('/') ? endpoint.urlPattern : `/${endpoint.urlPattern}`;
    const method = endpoint.method.toLowerCase();
    const operations = (paths[path] ??= {}) as Json;
    if (operations[method]) continue; // first observation wins
    operations[method] = buildOperation(endpoint);
    tags.add(endpoint.category);
  }

  const origins = [...new Set(report.endpoints.flatMap((e) => e.origins))];
  return {
    openapi: '3.0.3',
    info: {
      title: `API surface of ${host}`,
      description:
        `Best-effort OpenAPI spec generated by api-recon v${TOOL_VERSION} from observed ` +
        `browser traffic. Schemas are inferred from ${report.endpoints.length} endpoint patterns ` +
        `captured on ${new Date(report.meta.startedAt).toISOString()}.`,
      version: TOOL_VERSION,
    },
    servers: origins.length > 0 ? origins.map((url) => ({ url })) : [{ url: report.meta.seedUrl }],
    tags: [...tags].sort().map((name) => ({ name })),
    paths,
  };
}

function buildOperation(endpoint: Endpoint): Json {
  const parameters: Json[] = [
    ...endpoint.pathParams.map((name) => ({
      name,
      in: 'path',
      required: true,
      schema: { type: 'string' },
    })),
    ...endpoint.queryParams.map((q) => ({
      name: q.name,
      in: 'query',
      required: false,
      schema: { type: inferScalarType(q.sampleValues) },
      ...(q.sampleValues.length ? { example: q.sampleValues[0] } : {}),
    })),
  ];

  const responses: Record<string, Json> = {};
  for (const status of endpoint.statusCodes.length ? endpoint.statusCodes : [0]) {
    const key = status === 0 ? 'default' : String(status);
    const description = status === 0 ? 'Request failed (no response)' : `${status} response`;
    // Each error status carries its own contract when one was observed; the
    // success schema is only a fallback for a status with no captured body.
    const contract = endpoint.errorResponses?.find((error) => error.status === status);
    const schema = toOpenApiSchema(contract ? contract.schema : endpoint.responseSchema);
    // A schema can be absent or only partly observed; carry why as an
    // extension so the gap is documented rather than silently blank.
    const schemaReason = contract ? contract.schemaReason : endpoint.responseSchemaReason;
    responses[key] = {
      description,
      ...(Object.keys(schema).length ? { content: { 'application/json': { schema } } } : {}),
      ...(schemaReason ? { 'x-schema-reason': schemaReason } : {}),
    };
  }

  const hasBody = endpoint.requestBodySample !== null || endpoint.requestBodySchema !== null;
  const requestSchema = toOpenApiSchema(endpoint.requestBodySchema);

  return {
    summary: `${endpoint.method} ${endpoint.urlPattern}`,
    operationId: operationId(endpoint),
    tags: [endpoint.category],
    ...(parameters.length ? { parameters } : {}),
    ...(hasBody && BODY_METHODS.has(endpoint.method)
      ? {
          requestBody: {
            content: {
              'application/json': {
                schema: Object.keys(requestSchema).length ? requestSchema : { type: 'object' },
              },
            },
            ...(endpoint.requestBodySchemaReason
              ? { 'x-schema-reason': endpoint.requestBodySchemaReason }
              : {}),
          },
        }
      : {}),
    responses,
    'x-observed-count': endpoint.count,
    'x-observed-origins': endpoint.origins,
    ...(endpoint.graphql
      ? {
          'x-graphql-operations': endpoint.graphql.operations.map((op) =>
            op.name ? `${op.type} ${op.name}` : `${op.type} (anonymous)`,
          ),
          ...(endpoint.graphql.introspection ? { 'x-graphql-introspection': true } : {}),
        }
      : {}),
  };
}

function operationId(endpoint: Endpoint): string {
  return (
    endpoint.method.toLowerCase() +
    endpoint.urlPattern
      .replace(/\{([^}]+)\}/g, 'by-$1')
      .replace(/[^a-zA-Z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
  );
}

export function toOpenApiSchema(schema: JsonSchemaLike | null): Json {
  if (!schema) return {};
  const out: Json = {};
  if (schema.type === 'null') {
    out.type = 'string';
    out.nullable = true;
  } else if (schema.type && schema.type !== 'any') {
    out.type = schema.type;
  }
  if (schema.oneOf?.length) out.oneOf = schema.oneOf.map(toOpenApiSchema);
  if (schema.properties) {
    out.properties = Object.fromEntries(
      Object.entries(schema.properties).map(([k, v]) => [k, toOpenApiSchema(v)]),
    );
  }
  if (schema.items) out.items = toOpenApiSchema(schema.items);
  if (schema.required?.length) out.required = schema.required;
  if (schema.description && FORMAT_HINTS.has(schema.description)) out.format = schema.description;
  if (schema.enum?.length) out.enum = schema.enum;
  if (schema.minimum !== undefined) out.minimum = schema.minimum;
  if (schema.maximum !== undefined) out.maximum = schema.maximum;
  return out;
}

function inferScalarType(values: string[]): string {
  if (values.length > 0 && values.every((v) => /^-?\d+$/.test(v))) return 'integer';
  if (values.length > 0 && values.every((v) => /^-?\d*\.\d+$/.test(v))) return 'number';
  if (values.length > 0 && values.every((v) => v === 'true' || v === 'false')) return 'boolean';
  return 'string';
}

function safeHost(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}

export async function writeOpenApiReport(report: ReconReport, outDir: string): Promise<string> {
  await mkdir(outDir, { recursive: true });
  const file = join(outDir, FORMAT_FILENAMES.openapi);
  const spec = buildOpenApi(report);
  const yaml = dumpYaml(spec, { lineWidth: 100, noRefs: true, sortKeys: false });
  await writeFile(
    file,
    `# Generated by api-recon v${TOOL_VERSION} — review before use.\n${yaml}`,
    'utf8',
  );
  return file;
}
