# api-recon bash completion — generated by `api-recon completion bash`.
# Install: source <(api-recon completion bash), or drop it in bash_completion.d.
_api_recon_completions() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local flags="--version -V --depth -d --max-pages -m --open --print --preset --config --no-config --out -o --formats -f --browser -b --auth -a --login -l --record --actions --rate -r --respect-robots --no-respect-robots --diff --baseline --fail-on-diff --include-third-party --redact --no-redact --force --allow-local --telemetry --telemetry-preview --max-body-mb --quiet -q --verbose -v --json-progress --debug --help -h"

  case "${prev}" in
    --browser) COMPREPLY=( $(compgen -W "chromium firefox webkit" -- "${cur}") ); return 0 ;;
    --preset) COMPREPLY=( $(compgen -W "quick deep ci" -- "${cur}") ); return 0 ;;
    --print) COMPREPLY=( $(compgen -W "md json openapi html" -- "${cur}") ); return 0 ;;
    --formats) COMPREPLY=( $(compgen -W "json md html pdf openapi dashboard" -- "${cur}") ); return 0 ;;
    --auth|--login|--actions|--config|--diff|--baseline) COMPREPLY=( $(compgen -f -- "${cur}") ); return 0 ;;
    --out) COMPREPLY=( $(compgen -d -- "${cur}") ); return 0 ;;
  esac

  if [[ "${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flags}" -- "${cur}") )
    return 0
  fi

  if [[ "${COMP_WORDS[1]}" == "completion" ]]; then
    COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
    return 0
  fi

  # The first positional word is the subcommand; later ones are the seed URL.
  local i seen=0
  for (( i=1; i < COMP_CWORD; i++ )); do
    [[ "${COMP_WORDS[i]}" != -* ]] && seen=1
  done
  if (( seen == 0 )); then
    COMPREPLY=( $(compgen -W "baseline completion" -- "${cur}") )
  fi
  return 0
}
complete -o default -F _api_recon_completions api-recon
